#### Direct Call

POST https://mbb-espi-fapp-dev-eac9cpguace4c9gd.southeastasia-01.azurewebsites.net/api/chat?code={{$dotenv api_key}}
content-type: application/json; charset=utf-8

{
    "session_id": "740a651d424b42f3b97801c57a296865",
    "user_query": "tiger protection"
}

### APIM Proxy

POST https://mbb-espi-apim-dev.azure-api.net/api/chat
content-type: application/json; charset=utf-8

{
    "conversation_id": "740a651d424b42f3b97801c57a296866",
    "question": "tiger protection"
}